name: CI

on: [push, pull_request]

jobs:
  CI:
    runs-on: ubuntu-20.04

    strategy:
      fail-fast: false
      matrix:
        python-version: [3.9]

    steps:

    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: ls and pwd
      run: |
        id
        ls -l
        pwd
      
    - name: install gyronimo requirements
      run: |
        sudo apt-get update
        sudo apt-get install -y git gfortran openmpi-bin libopenmpi-dev gfortran gcc-10 g++-10 gcc-10-base libnetcdf-dev libnetcdff-dev libhdf5-openmpi-dev hdf5-tools libgsl-dev libboost-dev doxygen
        sudo apt-get install -y libblas-dev liblapack-dev python3 python3-numpy python3-h5py pgplot5 libncarg-dev libscalapack-openmpi-dev python3-pip libnetcdf-c++4-dev cmake

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: which python after python setup
      run: python --version

    - name: Install required python packages
      run: |
        alias pip=pip3
        alias python=python3
        python -m pip install --upgrade pip
        pip install matplotlib numpy scipy ninja cmake joblib scikit-build pybind11 f90wrap ninja toml
    
    - name: env after adding python
      run: env

    - name: PWD
      run: pwd

    - name: ls
      run: ls

    - name: Add to LD_LIBRARY_PATH so scalapack etc can be found
      run: echo "LD_LIBRARY_PATH=/usr/lib/x86_64-linux-gnu" >> $GITHUB_ENV

    # - name: Install simsopt
    #   run: |
    #     pip install simsopt

    # - name: Try running simsopt
    #   run: |
    #     python -c "import simsopt; print('success')"

    - name: Install NEAT
      run: |
        cp cmake_config_files/ubuntu.json cmake_config_file.json
        python3 setup.py build
        python3 setup.py install

    - name: ls
      run: ls

    - name: Install pyQSC
      run: |
        cd /home/external
        git clone https://github.com/landreman/pyQSC.git
        cd /home/external/pyQSC
        pip3 install .

    - name: ls
      run: ls

    - name: Try importing vmec module
      run: python -c "print(dir()); import vmec; print(dir()); print(dir(vmec)); print('package:', vmec.__package__); print('spec:', vmec.__spec__); print('doc:', vmec.__doc__); print('file:', vmec.__file__); print('path:', vmec.__path__)"

    # - name: Try running simple
    #   run: |
    #     cd build/bin
    #     ./simple.x

    - name: Run unit tests
      run: |
        python -m unittest -v
