name: CI

on: [push, pull_request]

jobs:
  CI:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        python-version: [3.9]

    steps:

    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        submodules: 'true'
        recursive submodules: 'true'
        token: ${{secrets.CI_TOKEN}}
        # token: ${ CI_TOKEN }

    - name: checkout gyronimo
      uses: actions/checkout@v2
      with:
        repository: prodrigs/gyronimo
        token: ${{ secrets.CI_TOKEN }}
        # token: ${ CI_TOKEN }
        ref: development
        path: external/gyronimo

    - name: Print user and group id
      run: id

    - name: PWD
      run: pwd

    - name: ls
      run: ls
      
    - name: install gyronimo requirements
      run: |
        sudo apt-get update
        sudo apt-get install -y wget git less make gsl-bin libgsl-dev libgslcblas0 cmake libboost-all-dev doxygen gcc-10 g++-10 gcc-10-base python3-dev python3-pip pkg-config software-properties-common

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: which python after python setup
      run: python --version

    - name: Install required python packages
      run: |
        python -m pip install --upgrade pip
        pip install wheel matplotlib numpy scipy ninja cmake pybind11 joblib qsc
        alias pip=pip3
        alias python=python3
    
    - name: env after adding python
      run: env

    - name: PWD
      run: pwd

    - name: ls
      run: ls

    - name: Configure and install gyronimo
      run: |
        cd external/gyronimo
        mkdir -p build
        cd build
        CXX=g++-10 cmake -DCMAKE_INSTALL_PREFIX=../../../build ../
        cmake --build . --target install 

    - name: Install NEAT
      run: |
        cd ../../../src
        g++-10 -std=c++2a -fPIC -shared NEAT.cc -o NEAT.so $(python3 -m pybind11 --includes) -L/usr/lib -lgsl -L../build/lib -lgyronimo -I../build/include/ -Wl,-rpath ../build/lib

    - name: Run unit tests
      run: |
        cd ../
        python -m unittest -v
